"""adding search_vector, ai_summary columns, gin index and pgtrgm extension

Revision ID: f90ac0a7698e
Revises: 9873ebaafeba
Create Date: 2026-05-09 22:29:10.050277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f90ac0a7698e'
down_revision: Union[str, Sequence[str], None] = '9873ebaafeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('posts', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.create_index('post_serch_idx', 'posts', ['search_vector'], unique=False, postgresql_using='gin')
    op.execute("""
        CREATE OR REPLACE FUNCTION update_posts_search_vector()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english', coalesce(NEW.title, '') || ' ' || coalesce(NEW.content, ''));
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER posts_serach_vector_update
        BEFORE INSERT OR UPDATE OF title, content
        ON posts
        FOR EACH ROW
        EXECUTE FUNCTION update_posts_search_vector();
    """)

    op.execute("""
        UPDATE posts 
        set search_vector = to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''));
    """)

    op.execute("""
        CREATE EXTENSION IF NOT EXISTS pg_trgm;
    """)

    op.execute("""
        CREATE INDEX post_title_trgm_idx
        ON posts
        USING GIN(title gin_trgm_ops);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS posts_search_vector_update ON posts")
    op.execute("DROP FUNCTION IF EXISTS update_posts_search_vector")
    op.drop_index('posts_search_idx', table_name='posts')
    op.drop_index('posts_title_trgm_idx', table_name='posts')
    op.drop_column('posts', 'search_vector')
    # ### end Alembic commands ###
